# Generated by Django 5.2.16 on 2026-07-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darsliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('mavzu', models.CharField(max_length=50)),
                ('malumotlar', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'darslik',
            },
        ),
    ]
