# Generated by Django 5.2.16 on 2026-07-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darsliklar', '0001_initial'),
        ('fanlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darsliklar',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='darsliklar', to='fanlar.fanlar'),
        ),
    ]
