# Generated by Django 5.2.16 on 2026-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanlar',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
