# Generated by Django 5.2.16 on 2026-07-18 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanlar', '0002_alter_fanlar_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SotibOlinganFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotib_olingan_sana', models.DateTimeField(auto_now_add=True)),
                ('tolov_holati', models.BooleanField(default=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotib_olganlar', to='fanlar.fanlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotib_olgan_fanlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sotib_olingan_fanlar',
                'unique_together': {('user', 'fan')},
            },
        ),
    ]
