# Generated by Django 5.2.16 on 2026-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek', models.ImageField(upload_to='chek')),
            ],
            options={
                'db_table': 'chek',
            },
        ),
    ]
